apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-app-deployment
  labels:
    app: quote-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quote-app-deployment
  template:
    metadata:
      labels:
        app: quote-app-deployment
    spec:
      containers:
      - name: quote-app
        image: quote-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: quote-app-service
  labels:
    app: quote-app-deployment
spec:
  type: ClusterIP
  selector:
    app: quote-app-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
